<?php echo $this->partial('partial/title', [
    'title' => $this->translate('Sections')
]); ?>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h5 class="mb-0">
                    <?php echo $this->translate('Delete section'); ?>
                </h5>
            </div>
            <div class="col-md-6">
                <div class="btn-toolbar justify-content-end" role="toolbar">
                    <div class="btn-group" role="group">
                        <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'sections']);?>"
                           data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Back'); ?>">
                            <i class="fa fa-arrow-left"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if (count($sections) == 0): ?>
        <div class="card-body">
            <p class="h5"><?php echo $this->translate('0 sections'); ?>.</p>
        </div>
    <?php else: ?>
        <div class="table-responsive">
            <table class="table table-sm table-hover">
                <thead>
                <tr>
                    <th scope="col"><?php echo $this->translate('Name'); ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($sections as $i => $section): ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('vault/default', ['controller' => 'sections', 'action' => 'view', 'id' => $section->getId()]); ?>">
                                <?php echo $section->getName(); ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="card-body">
            <form method="post" name="delete" role="form" action="<?php echo $this->url('vault/default', ['controller' => 'sections', 'action' => 'delete']); ?>" id="delete">
                <input type="hidden" name="step" value="2">
                <input type="hidden" name="items" value="<?php echo $this->escapeHtmlAttr($items); ?>">
                <input type="hidden" name="confirm" value="1">
                <div class="form-group mb-0">
                    <input type="submit" name="submit" class="btn btn-danger" id="submit" value="<?php echo $this->translate('Delete'); ?>">
                </div>
            </form>
        </div>
    <?php endif; ?>
</div>
