<?php echo $this->partial('partial/title', [
    'title' => $this->translate('Sections')
]); ?>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <h5 class="mb-0">
                    <?php echo $this->translate('Delete section'); ?>
                </h5>
            </div>
            <div class="col-md-6">
                <div class="btn-toolbar justify-content-end" role="toolbar">
                    <div class="btn-group mr-2" role="group">
                        <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'sections', 'action' => 'view', 'id' => $section->getId()]); ?>"
                           data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('View'); ?>">
                            <i class="fa fa-search-plus"></i>
                        </a>
                    </div>
                    <div class="btn-group mr-2" role="group">
                        <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'sections', 'action' => 'edit', 'id' => $section->getId()]); ?>"
                           data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Edit'); ?>">
                            <i class="fa fa-pencil"></i>
                        </a>
                    </div>
                    <div class="btn-group" role="group">
                        <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'sections']);?>"
                           data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Back'); ?>">
                            <i class="fa fa-arrow-left"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body">
        <form method="post" name="delete" role="form" action="<?php echo $this->url('vault/default', ['controller' => 'sections', 'action' => 'delete', 'id' => $section->getId()]); ?>" id="delete">
            <?php echo $this->partial('_view'); ?>

            <div class="form-group">
                <input type="submit" name="submit" class="btn btn-danger" id="submit" value="<?php echo $this->translate('Delete'); ?>">
            </div>
        </form>
    </div>
</div>
