<div class="form-row">
    <div class="col-sm-5 col-md-4 col-lg-3">
        <div class="form-group">
            <label class="font-weight-bold"><?php echo $this->translate('Avatar'); ?></label>
            <div class="form-control-plaintext">
                <img width="128" height="128" src="<?php echo $this->basePath($user->getAvatar()); ?>">
            </div>
        </div>
    </div>
    <div class="col-sm-7 col-md-8 col-lg-9">
        <div class="form-group">
            <label class="font-weight-bold"><?php echo $this->translate('Name'); ?></label>
            <div class="form-control-plaintext"><?php echo $user->getName(); ?></div>
        </div>
        <div class="form-group">
            <label class="font-weight-bold"><?php echo $this->translate('Email'); ?></label>
            <p class="form-control-plaintext"><?php echo $user->getEmail(); ?></p>
        </div>
        <div class="form-group">
            <label class="font-weight-bold"><?php echo $this->translate('Genre'); ?></label>
            <p class="form-control-plaintext"><?php echo $this->translate($user->getGender() === \Zetta\ZendAuthentication\Entity\Enum\Gender::FEMALE ? 'Female' : 'Male'); ?></p>
        </div>
        <div class="form-group">
            <label class="font-weight-bold"><?php echo $this->translate('Birthday'); ?></label>
            <p class="form-control-plaintext"><?php echo $user->getBirthday() ? $user->getBirthday()->format('d/m/Y') : '-'; ?></p>
        </div>
    </div>
</div>