<?php echo $this->partial('partial/title', ['title' => $this->translate('Users')]); ?>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6 mb-3 mb-md-0">
                <a class="btn btn-sm btn-success" href="<?php echo $this->url('home/default', ['controller' => 'users', 'action' => 'add']); ?>">
                    <i class="fa fa-plus"></i> <?php echo $this->translate('Add User'); ?>
                </a>
            </div>
            <div class="col-md-6">
                <?php echo $this->form()->openTag($searchForm); ?>
                    <div class="input-group input-group-sm ml-auto">
                        <?php echo $this->formElement($searchForm->get('q')); ?>
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>

    </div>
    <?php if (count($users) == 0): ?>
        <div class="card-body">
            <p class="h5"><?php echo $this->translate('0 user'); ?>.</p>
        </div>
    <?php else: ?>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col" class="text-right" style="width: 52px;">
                        #
                    </th>
                    <th scope="col">
                        <?php echo $this->translate('Name'); ?>
                    </th>
                    <th scope="col">
                        <?php echo $this->translate('Role'); ?>
                    </th>
                    <th scope="col" class="text-center" style="width: 175px">
                        <?php echo $this->translate('Actions'); ?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php
                $i = 1;
                foreach ($users as $user): ?>
                    <tr>
                        <th scope="row" class="text-right">
                            <?php echo $users->getAbsoluteItemNumber($i++); ?>
                        </th>
                        <td>
                            <a href="<?php echo $this->url('home/default', ['controller' => 'users', 'action' => 'view', 'id' => $user->getId()]); ?>">
                                <?php echo $user->getName() ?: '-'; ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $user->getRole()->getName(); ?>
                        </td>

                        <td class="text-center">
                            <a class="btn btn-link p-0" href="<?php echo $this->url('home/default', ['controller' => 'users', 'action' => 'edit', 'id' => $user->getId()]); ?>"
                               data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Edit'); ?>">
                                <i class="fa fa-fw fa-pencil"></i>
                            </a>
                            <a class="btn btn-link p-0" href="<?php echo $this->url('home/default', ['controller' => 'users', 'action' => 'delete', 'id' => $user->getId()]); ?>"
                               data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Delete'); ?>">
                                <i class="fa fa-fw fa-trash-o"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <?php echo $this->zettaPaginator($users); ?>
        </div>
    <?php endif; ?>
</div>
