<?php if (count($accounts) === 0): ?>
    <main class="col-12 col-md-9 col-xl-9 content-body" role="main">
        <h1><?php echo $this->translate('Credentials'); ?></h1>

        <div class="card">
            <div class="card-body">
                <p class="h5"><?php echo $this->translate('No account found'); ?>.</p>
            </div>
        </div>
    </main>
<?php else: ?>
    <div class="row flex-xl-nowrap">
        <div class="d-none d-xl-block col-xl-3 nav-topic" id="main-nav-topic">
            <ul class="section-nav border-secondary">
                <?php foreach ($accounts as $account): ?>
                <li class="nav-topic-item nav-topic-h2">
                    <a href="#account-<?php echo $account->getId(); ?>"><?php echo $account->getName(); ?></a>

                    <?php if (count($account->getSections()) > 0): ?>
                        <ul>
                            <?php foreach ($account->getSections() as $section): ?>
                                <li class="nav-topic-item nav-topic-h3">
                                    <a href="#section-<?php echo $account->getId(); ?>-<?php echo $section->getId(); ?>"><?php echo $section->getName(); ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <main class="col-12 col-md-9 col-xl-9 content-body" role="main">
            <h1><?php echo $this->translate('Credentials'); ?></h1>

            <?php foreach ($accounts as $account): ?>
                <h2 id="account-<?php echo $account->getId(); ?>" class="text-center">
                    <?php echo $account->getName(); ?>
                    <?php foreach ($account->getTags() as $tag): ?>
                        <span class="badge badge-info"><?php echo $tag->getName(); ?></span>
                    <?php endforeach; ?>
                </h2>

                <?php foreach ($account->getSections() as $section): ?>
                    <div class="card mb-3">
                        <div class="card-body">
                            <h3 id="section-<?php echo $account->getId(); ?>-<?php echo $section->getId(); ?>" class="card-title h5"><?php echo $section->getName(); ?></h3>
                            <?php if ($section->getDescription() !== null): ?>
                                <h6 class="card-subtitle mb-2 text-muted"><?php echo $section->getDescription(); ?></h6>
                            <?php endif; ?>
                        </div>
                        <table class="table table-sm table-hover">
                            <thead>
                            <tr>
                                <th scope="col" style="width: 12em;"><?php echo $this->translate('Name'); ?></th>
                                <th scope="col" ><?php echo $this->translate('Description'); ?></th>
                                <th scope="col" class="text-center" style="width: 3em;"><span class="sr-only">Ações</span></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($credentialsByAccount[$account->getId()][$section->getId()] as $credential): ?>
                                <tr>
                                    <td scope="row">
                                        <div class="text-ellipsis" style="width: 12em;">
                                            <a href="#more" data-id="<?php echo $credential->getId(); ?>">
                                                <i class="fa fa-fw fa-angle-right"></i>
                                                <?php if ($credential->getName() !== null) {
                                                    echo $credential->getName();
                                                } elseif ($credential->getSection() !== null) {
                                                    echo $credential->getSection()->getName();
                                                } elseif ($credential->getAccount() !== null) {
                                                    echo $credential->getAccount()->getName();
                                                } else {
                                                    echo $this->crypt()->decrypt($credential->getUsername());
                                                } ?>
                                            </a>
                                        </div>
                                    </td>
                                    <td>
                                        <?php echo $credential->getDescription() !== null ? $credential->getDescription() : ($credential->getSection() !== null ? $credential->getSection()->getDescription() : ''); ?>

                                        <?php foreach ($credential->getTags() as $tag): ?>
                                            <span class="badge badge-warning"><?php echo $tag->getName(); ?></span>
                                        <?php endforeach; ?>
                                    </td>

                                    <td class="btn-toolbar justify-content-center">
                                        <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'edit')): ?>
                                        <div class="btn-group">
                                            <div class="dropdown">
                                                <a class="btn-table btn-outline-secondary" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fa fa-fw fa-ellipsis-h"></i>
                                                </a>

                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" href="<?php echo $this->url('vault/default', ['controller' => 'credentials', 'action' => 'edit', 'id' =>  $credential->getId()]); ?>" target="_blank"><?php echo $this->translate('Edit'); ?></a>
                                                    <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'members')): ?>
                                                        <a class="dropdown-item" href="<?php echo $this->url('vault/default', ['controller' => 'credentials', 'action' => 'members', 'id' =>  $credential->getId()]); ?>" target="_blank"><?php echo $this->translate('Members'); ?></a>
                                                    <?php endif; ?>
                                                    <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'delete')): ?>
                                                        <a class="dropdown-item" href="<?php echo $this->url('vault/default', ['controller' => 'credentials', 'action' => 'delete', 'id' =>  $credential->getId()]); ?>" target="_blank"><?php echo $this->translate('Delete'); ?></a>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                <tr class="extra-info no-hover">
                                    <td></td>
                                    <td>
                                        <div class="text-primary text-center" id="<?php echo 'credential-' . $credential->getId() . '-spin'; ?>">
                                            <i class="fa fa-circle-o-notch fa-spin" style="font-size: 4.5em"></i>
                                        </div>
                                        <table class="table table-borderless mb-1 d-none">
                                            <tbody class="border-bottom">
                                            <tr class="no-hover">
                                                <th style="width: 12em;"><?php echo $this->translate('Username'); ?></th>
                                                <td class="credential-username">
                                                    <span></span>
                                                    <button type="button" class="btn btn-link p-0 border-0 align-baseline d-none" data-clipboard><i class="fa fa-fw fa-clone"></i></button>
                                                </td>
                                            </tr>
                                            <tr class="no-hover">
                                                <th><?php echo $this->translate('Password'); ?></th>
                                                <td class="credential-value">
                                                    <span></span>
                                                    <button type="button" class="btn btn-link p-0 border-0 align-baseline d-none" data-clipboard><i class="fa fa-fw fa-clone"></i></button>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                    <td></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </main>
    </div>
<?php endif; ?>
