<?php echo $this->doctype(); ?>

<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->prependName('keywords', 'zetta code, responsive layout')
            ->prependName('description', 'Vault')
            ->prependName('author', 'Zetta Code')
            ->prependName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
            ->prependHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <?php echo $this->headTitle($this->translate('Vault'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Fav and touch icons -->
        <link href="<?php echo $this->basePath('img/favicon.png'); ?>" rel="icon">
        <link href="<?php echo $this->basePath('img/apple-touch-icon.png'); ?>" rel="apple-touch-icon">

        <!-- Le styles -->
        <?php echo $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('assets/animate.min.css'))
            ->prependStylesheet($this->basePath('assets/selectize/css/selectize.bootstrap4.css'))
            ->prependStylesheet($this->basePath('assets/bootstrap-select/css/bootstrap-select.min.css'))
            ->prependStylesheet($this->basePath('assets/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/beagle.css'))
            ->prependStylesheet($this->basePath('assets/bootstrap/css/bootstrap.min.css')); ?>

        <!-- Le inline styles -->
        <?php echo $this->headStyle(); ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script type="text/javascript" src="<?php echo $this->basePath('js/html5shiv.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('js/respond.min.js'); ?>"></script>
        <![endif]-->

        <!-- Start Scripts -->
        <?php echo $this->headScript(); ?>
        <!--  End Scripts-->
    </head>
    <body>
        <!-- Start Navbar-->
        <?php echo $this->render('layout/default/navbar'); ?>
        <!-- End Navbar-->

        <!-- Start Content-->
        <div class="container-fluid">
            <div class="row flex-xl-nowrap justify-content-around">
                <div class="col-12 col-md-3 col-xl-2 zc-sidebar collapse show" id="sidebar-nav">
                    <!-- Start Navbar-->
                    <?php echo $this->render('layout/default/sidebar'); ?>
                    <!-- End Navbar-->
                </div>
                <div class="col-12 col-md-9 col-xl-10 py-3 pl-md-4 zc-content">
                    <?php if ($this->placeholder('title')->getValue()): ?>
                        <div class="page-head">
                            <h2 class="page-head-title"><?php echo $this->placeholder('title')->getValue(); ?></h2>
                            <?php if (!isset($breadcumb)): ?>
                                <?php echo $this->navigation('Zend\Navigation\Breadcrumbs')->breadcrumbs()->setPartial('partial/breadcrumbs') ;?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>

                    <!-- Start FlashMesseger-->
                    <?php echo $this->zettaFlashMessenger(); ?>
                    <!-- End FlashMesseger-->

                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <!-- End Content-->

        <!-- Start Footer-->
        <?php echo $this->render('layout/default/footer'); ?>
        <!-- End Footer-->

        <!-- Javascripts -->
        <!-- Important javascript libs(put in all pages) -->
        <script type="text/javascript" src="<?php echo $this->basePath('assets/jquery/jquery-3.2.1.min.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('assets/jquery/jquery.mask.min.js'); ?>"></script>
        <script type="text/javascript">var basePath = '<?php echo $this->basePath(); ?>';</script>

        <!-- Start Inline Scripts-->
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath('js/default.js'))
            ->prependFile($this->basePath('assets/selectize/js/standalone/selectize.min.js'))
            ->prependFile($this->basePath('assets/bootstrap-select/js/i18n/defaults-pt_BR.js'))
            ->prependFile($this->basePath('assets/bootstrap-select/js/bootstrap-select.min.js'))
            ->prependFile($this->basePath('assets/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/popper.min.js'))
            ->prependFile($this->basePath('assets/anchorjs/anchor.min.js'))
            ->prependFile($this->basePath('assets/clipboardjs/clipboard.min.js')); ?>
        <!-- End Inline Scripts-->
    </body>
</html>
