<?php echo $this->partial('partial/title', [
    'headTitle' => $this->translate('Accounts'),
    'title' => '<strong>' . $account->getName() . ': </strong>' . $this->translate('Members')
]); ?>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->zettaFormRow($form->get('member')); ?>

                    <?php echo $this->formRow($form->get('submit-btn')); ?>

                <?php echo $this->form()->closeTag(); ?>
            </div>
            <div class="col-md-6">
                <div class="btn-toolbar justify-content-end" role="toolbar">
                    <div class="btn-group mr-2" role="group">
                        <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'accounts', 'action' => 'view', 'id' => $account->getId()]); ?>"
                           data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('View'); ?>">
                            <i class="fa fa-search-plus"></i>
                        </a>
                    </div>
                    <div class="btn-group mr-2" role="group">
                        <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'accounts', 'action' => 'edit', 'id' => $account->getId()]); ?>"
                           data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Edit'); ?>">
                            <i class="fa fa-pencil"></i>
                        </a>
                    </div>
                    <div class="btn-group mr-2" role="group">
                        <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'accounts', 'action' => 'delete', 'id' => $account->getId()]); ?>"
                           data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Delete'); ?>">
                            <i class="fa fa-trash-o"></i>
                        </a>
                    </div>
                    <div class="btn-group" role="group">
                        <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'accounts']);?>"
                           data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Back'); ?>">
                            <i class="fa fa-arrow-left"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if (count($members) == 0): ?>
        <div class="card-body">
            <p class="h5"><?php echo $this->translate('No member found'); ?>.</p>
        </div>
    <?php else: ?>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col" class="text-right" style="width: 52px;">
                        #
                    </th>
                    <th scope="col">
                        <?php echo $this->translate('Name'); ?>
                    </th>
                    <th scope="col">
                        <?php echo $this->translate('Role'); ?>
                    </th>
                    <th scope="col" class="text-center" style="width: 175px">
                        <?php echo $this->translate('Actions'); ?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($members as $i => $member): ?>
                    <tr>
                        <th scope="row" class="text-right">
                            <?php echo $i + 1; ?>
                        </th>
                        <td>
                            <?php echo $member->getUser()->getName() ?: '-'; ?>
                        </td>
                        <td>
                            <?php echo $member->getUser()->getRole()->getName(); ?>
                        </td>

                        <td class="text-center">
                            <a class="btn btn-link p-0" href="<?php echo $this->url('vault/default', ['controller' => 'accounts', 'action' => 'revoke', 'id' => $member->getId()]); ?>"
                               data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->translate('Revoke'); ?>">
                                <i class="fa fa-fw fa-minus"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</div>
