<?php
echo $this->form()->openTag($form);
$credentialFieldset = $form->get('credential');
?>
    <?php echo $this->formHidden($credentialFieldset->get('id')); ?>

    <?php echo $this->zettaFormRow($credentialFieldset->get('name')); ?>

    <?php echo $this->zettaFormRow($credentialFieldset->get('username')); ?>

    <div class="form-group toogle-password">
        <?php echo $this->formLabel($credentialFieldset->get('value')); ?>
        <?php
        if (count($credentialFieldset->get('value')->getMessages()) !== 0) {
            $credentialFieldset->get('value')->setAttribute('class', $credentialFieldset->get('value')->getAttribute('class') . ' is-invalid');
        }
        echo $this->formElement($credentialFieldset->get('value')); ?>
        <i class="fa btn-toogle-password" onclick="togglePassword('#credential-value'); return false;"></i>
        <?php echo $this->formElementErrors($credentialFieldset->get('value'), ['class' => 'invalid-feedback']); ?>
    </div>

    <?php echo $this->zettaFormRow($credentialFieldset->get('account')); ?>

    <?php echo $this->zettaFormRow($credentialFieldset->get('section')); ?>

    <?php echo $this->zettaFormRow($credentialFieldset->get('description')); ?>

    <?php echo $this->zettaFormRow($credentialFieldset->get('tags')); ?>

    <div class="form-group">
        <?php echo $this->formRow($form->get('submit-btn')); ?>
    </div>
<?php echo $this->form()->closeTag(); ?>

<?php $this->inlineScript()
    ->appendFile($this->basePath('js/credentials/form.js')); ?>
