<div class="form-group">
    <label class="font-weight-bold"><?php echo $this->translate('Name'); ?></label>
    <p class="form-control-plaintext">
        <?php echo $credential->getName() ?: '-'; ?>
    </p>
</div>
<div class="form-group">
    <label class="font-weight-bold"><?php echo $this->translate('Username'); ?></label>
    <div class="form-inline">
        <div class="form-control mb-2 mr-2 flex-grow-1" style="width: auto;">
            <?php echo $this->crypt()->decrypt($credential->getUsername()); ?>
        </div>
        <button type="button" class="btn btn-light mb-2" data-clipboard data-clipboard-text="<?php echo $this->crypt()->decrypt($credential->getUsername()); ?>"><i class="fa fa-fw fa-lg fa-clone"></i></button>
    </div>
</div>
<div class="form-group">
    <label class="font-weight-bold"><?php echo $this->translate('Password'); ?></label>
    <div class="form-inline">
        <div class="form-control mb-2 mr-2 flex-grow-1" style="width: auto;">
                ●●●●●●
        </div>
        <button type="button" class="btn btn-light mx-2 mb-2 d-none"><i class="fa fa-fw fa-lg fa-eye"></i></button>
        <button type="button" class="btn btn-light mb-2" data-clipboard data-clipboard-text="<?php echo $this->crypt()->decrypt($credential->getValue()); ?>"><i class="fa fa-fw fa-lg fa-clone"></i></button>
        <div id="credential-secret" class="zv-secret d-none"><?php echo $credential->getValue(); ?></div>
    </div>
</div>
<div class="form-group">
    <label class="font-weight-bold"><?php echo $this->translate('Account'); ?></label>
    <p class="form-control-plaintext">
        <?php echo $credential->getAccount() != null ? $credential->getAccount()->getName() : '-'; ?>
    </p>
</div>
<div class="form-group">
    <label class="font-weight-bold"><?php echo $this->translate('Section'); ?></label>
    <p class="form-control-plaintext">
        <?php echo $credential->getSection() != null ? $credential->getSection()->getName() : '-'; ?>
    </p>
</div>
<div class="form-group">
    <label class="font-weight-bold"><?php echo $this->translate('Description'); ?></label>
    <p class="form-control-plaintext">
        <?php echo $credential->getDescription() ?: '-'; ?>
    </p>
</div>
<div class="form-group">
    <label class="font-weight-bold"><?php echo $this->translate('Tags'); ?></label>
    <?php if (count($credential->getTags()) === 0): ?>
        <p class="form-control-plaintext">
            <?php echo '-'; ?>
        </p>
    <?php else: ?>
        <p class="form-control-plaintext">
            <?php foreach ($credential->getTags() as $tag): ?>
                <span class="badge badge-warning"><?php echo $tag->getName(); ?></span>
            <?php endforeach; ?>
        </p>
    <?php endif; ?>
</div>