<?php echo $this->partial('partial/title', [
    'title' => $this->translate('Credentials')
]); ?>

<?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'add')): ?>
<div class="row mb-3">
    <div class="col-sm-4 col-md-3 mb-3 mb-md-0">
        <a class="btn btn-success" href="<?php echo $this->url('vault/default', ['controller' => 'credentials', 'action' => 'add']); ?>">
            <i class="fa fa-plus"></i> <?php echo $this->translate('Add credential'); ?>
        </a>
    </div>
</div>
<?php endif; ?>


<div class="card">
    <?php if (count($credentials) == 0): ?>
        <div class="card-body">
            <p class="h5"><?php echo $this->translate('0 credentials'); ?>.</p>
        </div>
    <?php else: ?>
        <div class="card-header">
            <div class="form-inline">
                <div class="form-group">
                    <label class="items-label my-1 mr-2">Nenhum item selecionado.</label>
                    <button class="btn btn-sm btn-outline-danger items-action items-btn d-none"
                            data-url="<?php echo $this->url('vault/default', ['controller' => 'credentials', 'action' => 'delete']); ?>">
                        <i class="fa fa-trash-o"></i> Excluir
                    </button>
                </div>
            </div>
        </div>
        <table class="table table-sm table-hover">
            <thead>
            <tr>
                <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'delete')): ?>
                <th scope="col" class="checkbox-cell">
                    <div class="custom-control custom-checkbox custom-checkbox-without-label">
                        <input class="custom-control-input items-all" type="checkbox" name="item-all" value="all" id="itemAll">
                        <label class="custom-control-label" for="itemAll"></label>
                    </div>
                </th>
                <?php endif; ?>
                <th scope="col" style="width: 12em;"><?php echo $this->translate('Name'); ?></th>
                <th scope="col" ><?php echo $this->translate('Description'); ?></th>
                <th scope="col" class="text-center" style="width: 3em;"><span class="sr-only">Ações</span></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($credentials as $i => $credential): ?>
                <tr>
                    <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'delete')): ?>
                    <th scope="row" class="checkbox-cell">
                        <div class="custom-control custom-checkbox custom-checkbox-without-label">
                            <input class="custom-control-input items-checkbox" type="checkbox" name="item-<?php echo $credential->getId(); ?>" id="itemCheckbox<?php echo $credential->getId(); ?>" value="<?php echo $credential->getId(); ?>">
                            <label class="custom-control-label" for="itemCheckbox<?php echo $credential->getId(); ?>"></label>
                        </div>
                    </th>
                    <?php endif; ?>
                    <td>
                        <div class="text-ellipsis" style="width: 12em;">
                        <a href="#more" data-id="<?php echo $credential->getId(); ?>">
                            <i class="fa fa-fw fa-angle-right"></i>
                            <?php if ($credential->getName() !== null) {
                                echo $credential->getName();
                            } elseif ($credential->getSection() !== null) {
                                echo $credential->getSection()->getName();
                            } elseif ($credential->getAccount() !== null) {
                                echo $credential->getAccount()->getName();
                            } else {
                                echo $this->crypt()->decrypt($credential->getUsername());
                            } ?>
                        </a>
                        </div>
                    </td>
                    <td>
                        <?php if ($credential->getAccount() != null && $credential->getSection() != null) {
                            echo '[<strong>' . $credential->getAccount()->getName() . '</strong> - ' . $credential->getSection()->getName() . ']';
                        } else if ($credential->getAccount() != null){
                            echo '[<strong>' . $credential->getAccount()->getName() . '</strong>]';
                        } else if ($credential->getSection() != null) {
                            echo '[' . $credential->getSection()->getName() . ']';
                        }?>

                        <?php echo $credential->getDescription() !== null ? $credential->getDescription() : ($credential->getSection() !== null ? $credential->getSection()->getDescription() : ''); ?>

                        <?php if ($credential->getAccount() != null): ?>
                            <?php foreach ($credential->getAccount()->getTags() as $tag): ?>
                                <span class="badge badge-info"><?php echo $tag->getName(); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <?php foreach ($credential->getTags() as $tag): ?>
                            <span class="badge badge-warning"><?php echo $tag->getName(); ?></span>
                        <?php endforeach; ?>
                    </td>

                    <td class="btn-toolbar justify-content-center">
                        <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'edit')): ?>
                            <div class="btn-group">
                                <div class="dropdown">
                                    <a class="btn-table btn-outline-secondary" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-fw fa-ellipsis-h"></i>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="<?php echo $this->url('vault/default', ['controller' => 'credentials', 'action' => 'edit', 'id' =>  $credential->getId()]); ?>"><?php echo $this->translate('Edit'); ?></a>
                                        <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'members')): ?>
                                            <a class="dropdown-item" href="<?php echo $this->url('vault/default', ['controller' => 'credentials', 'action' => 'members', 'id' =>  $credential->getId()]); ?>"><?php echo $this->translate('Members'); ?></a>
                                        <?php endif; ?>
                                        <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'delete')): ?>
                                            <a class="dropdown-item" href="<?php echo $this->url('vault/default', ['controller' => 'credentials', 'action' => 'delete', 'id' =>  $credential->getId()]); ?>"><?php echo $this->translate('Delete'); ?></a>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr class="extra-info no-hover">
                    <?php if ($this->isAllowed('Zetta\Vault\Controller\Credentials', 'delete')): ?>
                    <td></td>
                    <?php endif; ?>
                    <td></td>
                    <td>
                        <div class="text-primary text-center" id="<?php echo 'credential-' . $credential->getId() . '-spin'; ?>">
                            <i class="fa fa-circle-o-notch fa-spin" style="font-size: 4.5em"></i>
                        </div>
                        <table class="table table-borderless mb-1">
                            <tbody class="border-bottom">
                            <tr class="no-hover">
                                <th style="width: 12em;"><?php echo $this->translate('Username'); ?></th>
                                <td class="credential-username">
                                    <span></span>
                                    <button type="button" class="btn btn-link p-0 border-0 align-baseline d-none" data-clipboard><i class="fa fa-fw fa-clone"></i></button>
                                </td>
                            </tr>
                            <tr class="no-hover">
                                <th><?php echo $this->translate('Password'); ?></th>
                                <td class="credential-value">
                                    <span></span>
                                    <button type="button" class="btn btn-link p-0 border-0 align-baseline d-none" data-clipboard><i class="fa fa-fw fa-clone"></i></button>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                    <td></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div class="card-footer">
            <?php echo $this->zettaPaginator($credentials); ?>
        </div>
    <?php endif; ?>
</div>
