<?php
$title = $this->translate('Sign in');
$this->headTitle($title);
?>

<div class="splash-container">
    <div class="text-center mb-4">
        <a href="<?php echo $this->url($routes['home']['name'], $routes['home']['params'], $routes['home']['options'], $routes['home']['reuseMatchedParams']); ?>">
            <img src="<?php echo $this->basePath('img/brand.svg') ?>" height="256" class="logo-img" alt="<?php $this->translate('Vault'); ?>">
        </a>
    </div>
    <div class="card">
        <div class="card-body">
            <?php echo $this->zettaFlashMessenger(); ?>

            <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('username')); ?>
                </div>

                <div class="form-group">
                    <?php echo $this->formElement($form->get('password')); ?>
                </div>

                <div class="form-group row login-tools">
                    <div class="col-6 login-remember">
                        <?php echo $this->zettaFormRow($form->get('remember-me'), 'append'); ?>
                    </div>
                    <div class="col-6 login-forgot-password">
                        <a href="<?php echo $this->url($routes['recover']['name'], $routes['recover']['params'], $routes['recover']['options'], $routes['recover']['reuseMatchedParams']); ?>">
                            <?php echo $this->translate('Forgotten password'); ?>
                        </a>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow($form->get('submit-btn')); ?>
                </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
